// UI labels for the Staffing tab (EN/FI/SV). Kept beside the feature, like the Wiurila shift list.
export type StaffLang = "en" | "fi" | "sv";

const en = {
  tabNeeds: "Staffing needs",
  tabShifts: "Shift list",
  period: "Shift list",
  noPeriods: "No shift lists yet",
  newStart: "Starts (Mon)",
  length: "Length",
  len3w: "3 weeks",
  len1m: "1 month (5 weeks)",
  len3m: "3 months (13 weeks)",
  newPeriod: "New shift list",
  staffRegister: "Staff",
  settings: "Pay rules and ratios",
  history: "Change history",
  print: "Print",
  perWorker: "Worker sheet",
  exportCsv: "Download CSV",
  payrollExcel: "Payroll Excel",
  payrollError: "The payroll file could not be created. Please try again.",
  deletePeriod: "Delete list",
  confirmDeletePeriod: "Delete the whole shift list?",
  modePlanned: "Planned shifts",
  modeActual: "Realized hours",
  help: "Pick the role first, then the name. Type e.g. 10-18 or a code in a cell. Tab and arrow keys move between cells.",
  helpActual:
    "Enter realized times. Grey text shows the planned shift. An empty cell means not recorded yet.",
  legend:
    "V = weekly rest, X = public holiday off, Z = overtime off, L = annual leave, P = unpaid leave",
  role: "Role",
  worker: "Worker",
  vacant: "pick name",
  noRole: "no role",
  totalHours: "Hours",
  xz: "X/Z",
  sunday: "Sun/holiday h",
  evening: "Evening h",
  night: "Night h",
  holiday: "Leave",
  notes: "Notes",
  addRow: "Add row",
  removeRow: "Remove row",
  search: "Search name or role",
  allRoles: "All roles",
  allWorkers: "All workers",
  clearFilters: "Clear filters",
  noMatch: "No workers match your search",
  noMatchBody: "Try another name or role, or clear the filters.",
  badCell: "Type e.g. 10-18 or a code V, X, Z, L, P",
  badActual: "Type the realized time, e.g. 10-18:30",
  saved: "Saved",
  error: "Saving failed",
  tierLimit:
    "The Basic plan allows one shift list at a time. Delete the old list or upgrade.",
  upgradeActual:
    "Realized hours and downloads are included in Professional and Business.",
  upgradePayroll: "Payroll export and change history are included in Business.",
  upgradeNeeds: "Staffing needs are included in Professional and Business.",
  viewOnly:
    "Only owners and admins can change the shift list. You can record realized hours.",
  // register
  name: "Name",
  roles: "Roles",
  employment: "Employment",
  phone: "Phone",
  email: "Email",
  weeklyTarget: "Weekly hours",
  active: "Active",
  add: "Add",
  save: "Save",
  delete: "Delete",
  close: "Close",
  editRoles: "Roles",
  emp_regular: "Regular",
  emp_part_time: "Part time",
  emp_relief: "Relief",
  emp_intern: "Intern",
  addRole: "Add role",
  roleNameEn: "Name (English)",
  roleNameFi: "Name (Finnish)",
  roleNameSv: "Name (Swedish)",
  addDefaultRoles: "Add suggested roles",
  noStaff: "No staff yet. Add the people who work shifts.",
  contactsHint: "Phone and email are only visible to owners and admins.",
  // settings
  guestsPerStaff: "Guests per staff member",
  minStaff: "Minimum staff while a booking runs",
  hourlyCost: "Hourly cost (EUR)",
  eveningStart: "Evening starts",
  eveningEnd: "Evening ends",
  nightEnd: "Night ends",
  finnishHolidays: "Count Finnish public holidays as Sunday work",
  // needs
  day: "Day",
  guests: "Guests",
  needed: "Needed",
  rostered: "On shift",
  understaffed: "Understaffed",
  noBookings: "No bookings with a time on this day.",
  understaffedHours: "Understaffed hours",
  estCost: "Estimated staff cost",
  hour: "Hour",
  noList: "No shift list covers this day, so nobody counts as on shift.",
  historyNone: "No changes yet.",
};

type Labels = typeof en;

const fi: Labels = {
  tabNeeds: "Henkilöstötarve",
  tabShifts: "Vuorolista",
  period: "Vuorolista",
  noPeriods: "Ei vielä vuorolistoja",
  newStart: "Alkaa (ma)",
  length: "Pituus",
  len3w: "3 viikkoa",
  len1m: "1 kk (5 viikkoa)",
  len3m: "3 kk (13 viikkoa)",
  newPeriod: "Uusi vuorolista",
  staffRegister: "Henkilöstö",
  settings: "Palkkasäännöt ja mitoitus",
  history: "Muutoshistoria",
  print: "Tulosta",
  perWorker: "Työntekijän lista",
  exportCsv: "Lataa CSV",
  payrollExcel: "Palkanlaskenta Excel",
  payrollError: "Palkkatiedostoa ei voitu luoda. Yritä uudelleen.",
  deletePeriod: "Poista lista",
  confirmDeletePeriod: "Poistetaanko koko vuorolista?",
  modePlanned: "Suunnitellut vuorot",
  modeActual: "Toteutuneet tunnit",
  help: "Valitse ensin tehtävä, sitten nimi. Kirjoita soluun esim. 10-18 tai koodi. Sarkain ja nuolinäppäimet siirtävät solusta toiseen.",
  helpActual:
    "Kirjaa toteutuneet ajat. Harmaa teksti näyttää suunnitellun vuoron. Tyhjä solu tarkoittaa, ettei toteumaa ole vielä kirjattu.",
  legend:
    "V = viikkolepopäivä, X = arkipyhävapaa, Z = ylityövapaa, L = vuosiloma, P = palkaton vapaa",
  role: "Tehtävä",
  worker: "Työntekijä",
  vacant: "valitse nimi",
  noRole: "ei tehtävää",
  totalHours: "Tunnit",
  xz: "X/Z",
  sunday: "Su/pyhä h",
  evening: "Ilta h",
  night: "Yö h",
  holiday: "Loma",
  notes: "Huom",
  addRow: "Lisää rivi",
  removeRow: "Poista rivi",
  search: "Hae nimellä tai tehtävällä",
  allRoles: "Kaikki tehtävät",
  allWorkers: "Kaikki työntekijät",
  clearFilters: "Tyhjennä suodattimet",
  noMatch: "Haulla ei löytynyt työntekijöitä",
  noMatchBody: "Kokeile toista nimeä tai tehtävää, tai tyhjennä suodattimet.",
  badCell: "Kirjoita esim. 10-18 tai koodi V, X, Z, L, P",
  badActual: "Kirjoita toteutunut aika, esim. 10-18:30",
  saved: "Tallennettu",
  error: "Tallennus epäonnistui",
  tierLimit:
    "Basic-paketissa voi olla yksi vuorolista kerrallaan. Poista vanha lista tai vaihda pakettia.",
  upgradeActual:
    "Toteutuneet tunnit ja lataukset sisältyvät Professional- ja Business-paketteihin.",
  upgradePayroll:
    "Palkanlaskennan vienti ja muutoshistoria sisältyvät Business-pakettiin.",
  upgradeNeeds:
    "Henkilöstötarve sisältyy Professional- ja Business-paketteihin.",
  viewOnly:
    "Vain omistajat ja ylläpitäjät voivat muuttaa vuorolistaa. Voit kirjata toteutuneet tunnit.",
  name: "Nimi",
  roles: "Tehtävät",
  employment: "Työsuhde",
  phone: "Puhelin",
  email: "Sähköposti",
  weeklyTarget: "Viikkotunnit",
  active: "Aktiivinen",
  add: "Lisää",
  save: "Tallenna",
  delete: "Poista",
  close: "Sulje",
  editRoles: "Tehtävät",
  emp_regular: "Vakituinen",
  emp_part_time: "Osa-aikainen",
  emp_relief: "Tuuraaja",
  emp_intern: "Harjoittelija",
  addRole: "Lisää tehtävä",
  roleNameEn: "Nimi (englanti)",
  roleNameFi: "Nimi (suomi)",
  roleNameSv: "Nimi (ruotsi)",
  addDefaultRoles: "Lisää ehdotetut tehtävät",
  noStaff: "Ei vielä henkilöstöä. Lisää vuoroja tekevät henkilöt.",
  contactsHint:
    "Puhelin ja sähköposti näkyvät vain omistajille ja ylläpitäjille.",
  guestsPerStaff: "Vieraita työntekijää kohden",
  minStaff: "Vähintään työntekijöitä varauksen aikana",
  hourlyCost: "Tuntikustannus (EUR)",
  eveningStart: "Ilta alkaa",
  eveningEnd: "Ilta päättyy",
  nightEnd: "Yö päättyy",
  finnishHolidays: "Laske suomalaiset pyhäpäivät sunnuntaityöksi",
  day: "Päivä",
  guests: "Vieraat",
  needed: "Tarve",
  rostered: "Vuorossa",
  understaffed: "Alimitoitettu",
  noBookings: "Tälle päivälle ei ole kellonajallisia varauksia.",
  understaffedHours: "Alimitoitetut tunnit",
  estCost: "Arvioitu henkilöstökulu",
  hour: "Tunti",
  noList:
    "Mikään vuorolista ei kata tätä päivää, joten ketään ei lasketa vuoroon.",
  historyNone: "Ei vielä muutoksia.",
};

const sv: Labels = {
  tabNeeds: "Personalbehov",
  tabShifts: "Turlista",
  period: "Turlista",
  noPeriods: "Inga turlistor ännu",
  newStart: "Börjar (må)",
  length: "Längd",
  len3w: "3 veckor",
  len1m: "1 mån (5 veckor)",
  len3m: "3 mån (13 veckor)",
  newPeriod: "Ny turlista",
  staffRegister: "Personal",
  settings: "Löneregler och bemanning",
  history: "Ändringshistorik",
  print: "Skriv ut",
  perWorker: "Personlig lista",
  exportCsv: "Ladda ner CSV",
  payrollExcel: "Lön Excel",
  payrollError: "Lönefilen kunde inte skapas. Försök igen.",
  deletePeriod: "Ta bort lista",
  confirmDeletePeriod: "Ta bort hela turlistan?",
  modePlanned: "Planerade turer",
  modeActual: "Utförda timmar",
  help: "Välj uppgift först, sedan namn. Skriv t.ex. 10-18 eller en kod i cellen. Tabb och piltangenter flyttar mellan cellerna.",
  helpActual:
    "Skriv in utförda tider. Grå text visar planerad tur. En tom cell betyder att inget har registrerats ännu.",
  legend:
    "V = veckovila, X = helgdagsledighet, Z = övertidsledighet, L = semester, P = obetald ledighet",
  role: "Uppgift",
  worker: "Anställd",
  vacant: "välj namn",
  noRole: "ingen uppgift",
  totalHours: "Timmar",
  xz: "X/Z",
  sunday: "Sö/helg h",
  evening: "Kväll h",
  night: "Natt h",
  holiday: "Semester",
  notes: "Anm.",
  addRow: "Lägg till rad",
  removeRow: "Ta bort rad",
  search: "Sök namn eller uppgift",
  allRoles: "Alla uppgifter",
  allWorkers: "Alla anställda",
  clearFilters: "Rensa filter",
  noMatch: "Inga anställda matchar sökningen",
  noMatchBody: "Prova ett annat namn eller uppgift, eller rensa filtren.",
  badCell: "Skriv t.ex. 10-18 eller en kod V, X, Z, L, P",
  badActual: "Skriv utförd tid, t.ex. 10-18:30",
  saved: "Sparat",
  error: "Sparandet misslyckades",
  tierLimit:
    "Basic-paketet tillåter en turlista åt gången. Ta bort den gamla listan eller uppgradera.",
  upgradeActual:
    "Utförda timmar och nedladdningar ingår i Professional och Business.",
  upgradePayroll: "Löneexport och ändringshistorik ingår i Business.",
  upgradeNeeds: "Personalbehov ingår i Professional och Business.",
  viewOnly:
    "Endast ägare och administratörer kan ändra turlistan. Du kan registrera utförda timmar.",
  name: "Namn",
  roles: "Uppgifter",
  employment: "Anställning",
  phone: "Telefon",
  email: "E-post",
  weeklyTarget: "Veckotimmar",
  active: "Aktiv",
  add: "Lägg till",
  save: "Spara",
  delete: "Ta bort",
  close: "Stäng",
  editRoles: "Uppgifter",
  emp_regular: "Fast",
  emp_part_time: "Deltid",
  emp_relief: "Vikarie",
  emp_intern: "Praktikant",
  addRole: "Lägg till uppgift",
  roleNameEn: "Namn (engelska)",
  roleNameFi: "Namn (finska)",
  roleNameSv: "Namn (svenska)",
  addDefaultRoles: "Lägg till föreslagna uppgifter",
  noStaff: "Ingen personal ännu. Lägg till de som arbetar turer.",
  contactsHint: "Telefon och e-post syns bara för ägare och administratörer.",
  guestsPerStaff: "Gäster per anställd",
  minStaff: "Minst anställda medan en bokning pågår",
  hourlyCost: "Timkostnad (EUR)",
  eveningStart: "Kväll börjar",
  eveningEnd: "Kväll slutar",
  nightEnd: "Natt slutar",
  finnishHolidays: "Räkna finska helgdagar som söndagsarbete",
  day: "Dag",
  guests: "Gäster",
  needed: "Behov",
  rostered: "I tjänst",
  understaffed: "Underbemannat",
  noBookings: "Inga bokningar med tid denna dag.",
  understaffedHours: "Underbemannade timmar",
  estCost: "Beräknad personalkostnad",
  hour: "Timme",
  noList: "Ingen turlista täcker denna dag, så ingen räknas som i tjänst.",
  historyNone: "Inga ändringar ännu.",
};

export const STAFF_LABELS: Record<StaffLang, Labels> = { en, fi, sv };
export const staffLang = (l: string): StaffLang =>
  l === "fi" || l === "sv" ? l : "en";
