import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  ShieldCheck,
  FileText,
  ExternalLink,
  Download,
  Package,
  Bug,
  BookLock,
  Siren,
} from "lucide-react";

interface DocLink {
  title: string;
  description: string;
  href: string;
  external?: boolean;
  download?: boolean;
  icon: React.ComponentType<{ className?: string }>;
  badge?: string;
}

const DOCS: DocLink[] = [
  {
    title: "Software Bill of Materials (SBOM)",
    description:
      "CycloneDX 1.5 SBOM for the current release, regenerated by the `sbom` GitHub Action and checksummed.",
    href: "/security-docs/sbom.cdx.json",
    download: true,
    icon: Package,
    badge: "CycloneDX",
  },
  {
    title: "SBOM Checksum",
    description: "SHA-256 checksum of the SBOM, used to verify integrity of the downloaded file.",
    href: "/security-docs/sbom.cdx.json.sha256",
    download: true,
    icon: FileText,
  },
  {
    title: "Dependency Inventory",
    description:
      "Human-readable inventory of production and development dependencies, owners, and update policy.",
    href: "/security-docs/dependency-inventory.md",
    download: true,
    icon: FileText,
  },
  {
    title: "Vulnerability Scanning Pipeline",
    description:
      "How Dependabot, Aikido (workspace-wide), and CI audits combine to surface vulnerable dependencies.",
    href: "/security-docs/vulnerability-scanning.md",
    download: true,
    icon: Bug,
    badge: "Dependabot + Aikido",
  },
  {
    title: "Vulnerability Disclosure Policy",
    description:
      "Public-facing policy for reporting security issues, plus the /.well-known/security.txt contact.",
    href: "/security",
    icon: ShieldCheck,
    badge: "Public",
  },
  {
    title: "security.txt",
    description: "RFC 9116 machine-readable disclosure contact at /.well-known/security.txt.",
    href: "/.well-known/security.txt",
    download: true,
    icon: FileText,
  },
  {
    title: "Secure Development Documentation",
    description:
      "Secure SDLC: code review, RLS rules, secrets, dependency hygiene, and CI gates.",
    href: "/security-docs/secure-development.md",
    download: true,
    icon: BookLock,
  },
  {
    title: "Penetration Testing Policy",
    description:
      "Cadence, scope, and rules of engagement for internal and third-party penetration tests.",
    href: "/security-docs/penetration-testing-policy.md",
    download: true,
    icon: FileText,
  },
  {
    title: "Incident Response Plan",
    description:
      "Severity matrix, roles, GDPR 72-hour notification flow, evidence handling, and tabletop cadence.",
    href: "/security-docs/incident-response.md",
    download: true,
    icon: Siren,
    badge: "GDPR Art. 33/34",
  },
];

const SecurityDocsPanel = () => {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-xl font-serif flex items-center gap-2">
          <ShieldCheck className="h-5 w-5 text-primary" />
          Security & Compliance
        </CardTitle>
        <p className="text-sm text-muted-foreground mt-1">
          Centralized index of MimmoBook's security program documents, served directly from this
          app for one-click access during audits and incident response. Continuous scanning runs
          via Dependabot and Aikido; the documents below describe the policies, procedures, and
          artifacts behind those scans.
        </p>
      </CardHeader>
      <CardContent>
        <div className="grid gap-3 sm:grid-cols-2">
          {DOCS.map((doc) => {
            const Icon = doc.icon;
            const ActionIcon = doc.download ? Download : ExternalLink;
            return (
              <div
                key={doc.title}
                className="flex flex-col gap-2 rounded-lg border bg-card p-4 hover:border-primary/40 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <Icon className="h-4 w-4 text-primary shrink-0" />
                    <h3 className="font-medium text-sm leading-tight">{doc.title}</h3>
                  </div>
                  {doc.badge && (
                    <Badge variant="secondary" className="text-xs shrink-0">
                      {doc.badge}
                    </Badge>
                  )}
                </div>
                <p className="text-xs text-muted-foreground flex-1">{doc.description}</p>
                <Button asChild variant="outline" size="sm" className="w-fit">
                  <a
                    href={doc.href}
                    target={doc.external || doc.download ? "_blank" : undefined}
                    rel={doc.external || doc.download ? "noopener noreferrer" : undefined}
                    download={doc.download ? "" : undefined}
                  >
                    {doc.download ? "Download" : "Open"}
                    <ActionIcon className="ml-1.5 h-3 w-3" />
                  </a>
                </Button>
              </div>
            );
          })}
        </div>

        <div className="mt-4 rounded-md border border-dashed bg-muted/40 p-3 text-xs text-muted-foreground">
          <strong className="text-foreground">Continuous scanning:</strong> Dependabot raises pull
          requests for vulnerable npm dependencies. Aikido scans the workspace and surfaces
          findings in the Security tab. Findings are triaged within the SLAs defined in the
          Incident Response Plan.
        </div>
      </CardContent>
    </Card>
  );
};

export default SecurityDocsPanel;
