/**
 * Regression guard: payment links (checkout / billing portal URLs) and email
 * addresses must never be written to server logs. Scans every backend function
 * for log calls (console.* and logStep-style helpers) whose arguments mention a
 * URL or email value.
 */
import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(__dirname, "..", "..", "..");
const FUNCTIONS_DIR = join(ROOT, "supabase", "functions");

const LOG_CALL =
  /\b(?:console\.(?:log|info|warn|error|debug)|logStep|log(?:Info|Warn|Error|Event)?)\s*\(/g;

// Argument patterns that would leak a payment link or an email address.
const PAYMENT_LINK =
  /\b(?:session|portalSession|checkout|portal|link)\??\.url\b|\burl\s*:|\b(?:checkout|portal|payment)_?url\b/i;
const EMAIL =
  /\.email\b|\bemail\s*:|\b(?:customer|guest|user|recipient|to)_?email\b/i;

// Test-only helper: logs synthetic addresses generated by the test suite itself.
const ALLOWED = new Set(["test-cleanup.ts"]);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      if (name === "node_modules") continue;
      out.push(...walk(p));
    } else if (
      /\.ts$/.test(name) &&
      !/\.test\.ts$/.test(name) &&
      !ALLOWED.has(name)
    ) {
      out.push(p);
    }
  }
  return out;
}

/** Returns the text of the call's argument list (balanced parentheses). */
function callArgs(src: string, openIdx: number): string {
  let depth = 0;
  for (let i = openIdx; i < src.length; i++) {
    const c = src[i];
    if (c === "(") depth++;
    else if (c === ")" && --depth === 0) return src.slice(openIdx + 1, i);
  }
  return src.slice(openIdx + 1);
}

export function findLeaks(src: string): { kind: string; snippet: string }[] {
  const leaks: { kind: string; snippet: string }[] = [];
  for (const m of src.matchAll(LOG_CALL)) {
    const args = callArgs(src, (m.index ?? 0) + m[0].length - 1);
    // Ignore plain wording ("Failed to enqueue email:"); keep `${...}` values.
    const code = args
      .replace(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/g, '""')
      .replace(/`(?:[^`\\]|\\.)*`/g, (t) =>
        (t.match(/\$\{[^}]*\}/g) ?? []).join(" "),
      );
    const snippet = `${m[0]}${args})`.replace(/\s+/g, " ").slice(0, 160);
    if (PAYMENT_LINK.test(code)) leaks.push({ kind: "payment link", snippet });
    if (EMAIL.test(code)) leaks.push({ kind: "email address", snippet });
  }
  return leaks;
}

describe("payment links and email addresses stay out of logs", () => {
  it("detector catches the previously fixed leaks", () => {
    expect(
      findLeaks(
        `logStep("Checkout session created", { sessionId: session.id, url: session.url });`,
      ),
    ).not.toHaveLength(0);
    expect(
      findLeaks(
        `logStep("User authenticated", { userId: user.id, email: user.email });`,
      ),
    ).not.toHaveLength(0);
    expect(
      findLeaks("console.log(`portal ${portalSession.url}`)"),
    ).not.toHaveLength(0);
    expect(findLeaks(`logStep("Checkout session created");`)).toHaveLength(0);
  });

  it("checkout and subscription functions log neither", () => {
    for (const fn of ["create-checkout", "check-subscription"]) {
      const src = readFileSync(join(FUNCTIONS_DIR, fn, "index.ts"), "utf8");
      expect(findLeaks(src), fn).toEqual([]);
    }
  });

  it("no backend function logs a payment link", () => {
    const offenders = walk(FUNCTIONS_DIR).flatMap((f) =>
      findLeaks(readFileSync(f, "utf8"))
        .filter((l) => l.kind === "payment link")
        .map((l) => `${relative(ROOT, f)}: ${l.snippet}`),
    );
    expect(offenders).toEqual([]);
  });

  it("no backend function logs an email address", () => {
    const offenders = walk(FUNCTIONS_DIR).flatMap((f) =>
      findLeaks(readFileSync(f, "utf8"))
        .filter((l) => l.kind === "email address")
        .map((l) => `${relative(ROOT, f)}: ${l.snippet}`),
    );
    expect(offenders).toEqual([]);
  });
});
