/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as BetaGuideRouteImport } from './routes/beta-guide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FindBookingRouteImport } from './routes/find-booking'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as WhatIsMimmobookRouteImport } from './routes/what-is-mimmobook'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BookSlugRouteImport } from './routes/book/$slug'
import { Route as E2eEmailPreviewRouteImport } from './routes/e2e/email-preview'
import { Route as LegalDpaRouteImport } from './routes/legal/dpa'
import { Route as LegalRetentionRouteImport } from './routes/legal/retention'
import { Route as LegalSubprocessorsRouteImport } from './routes/legal/subprocessors'
import { Route as MyBookingTokenRouteImport } from './routes/my-booking/$token'
import { Route as OfferTokenRouteImport } from './routes/offer/$token'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SuperadminBlogJsonLdRouteImport } from './routes/superadmin/blog-json-ld'
import { Route as SuperadminGaDebugRouteImport } from './routes/superadmin/ga-debug'
import { Route as SuperadminGaValidateRouteImport } from './routes/superadmin/ga-validate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaGuideRoute = BetaGuideRouteImport.update({
  id: '/beta-guide',
  path: '/beta-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FindBookingRoute = FindBookingRouteImport.update({
  id: '/find-booking',
  path: '/find-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsMimmobookRoute = WhatIsMimmobookRouteImport.update({
  id: '/what-is-mimmobook',
  path: '/what-is-mimmobook',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eEmailPreviewRoute = E2eEmailPreviewRouteImport.update({
  id: '/e2e/email-preview',
  path: '/e2e/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/legal/dpa',
  path: '/legal/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRetentionRoute = LegalRetentionRouteImport.update({
  id: '/legal/retention',
  path: '/legal/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSubprocessorsRoute = LegalSubprocessorsRouteImport.update({
  id: '/legal/subprocessors',
  path: '/legal/subprocessors',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingTokenRoute = MyBookingTokenRouteImport.update({
  id: '/my-booking/$token',
  path: '/my-booking/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferTokenRoute = OfferTokenRouteImport.update({
  id: '/offer/$token',
  path: '/offer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminBlogJsonLdRoute = SuperadminBlogJsonLdRouteImport.update({
  id: '/superadmin/blog-json-ld',
  path: '/superadmin/blog-json-ld',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminGaDebugRoute = SuperadminGaDebugRouteImport.update({
  id: '/superadmin/ga-debug',
  path: '/superadmin/ga-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminGaValidateRoute = SuperadminGaValidateRouteImport.update({
  id: '/superadmin/ga-validate',
  path: '/superadmin/ga-validate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/beta-guide': typeof BetaGuideRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/find-booking': typeof FindBookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/use-cases': typeof UseCasesRoute
  '/what-is-mimmobook': typeof WhatIsMimmobookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/e2e/email-preview': typeof E2eEmailPreviewRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/retention': typeof LegalRetentionRoute
  '/legal/subprocessors': typeof LegalSubprocessorsRoute
  '/my-booking/$token': typeof MyBookingTokenRoute
  '/offer/$token': typeof OfferTokenRoute
  '/superadmin/blog-json-ld': typeof SuperadminBlogJsonLdRoute
  '/superadmin/ga-debug': typeof SuperadminGaDebugRoute
  '/superadmin/ga-validate': typeof SuperadminGaValidateRoute
  '/blog/': typeof BlogIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/beta-guide': typeof BetaGuideRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/find-booking': typeof FindBookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/use-cases': typeof UseCasesRoute
  '/what-is-mimmobook': typeof WhatIsMimmobookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/e2e/email-preview': typeof E2eEmailPreviewRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/retention': typeof LegalRetentionRoute
  '/legal/subprocessors': typeof LegalSubprocessorsRoute
  '/my-booking/$token': typeof MyBookingTokenRoute
  '/offer/$token': typeof OfferTokenRoute
  '/superadmin/blog-json-ld': typeof SuperadminBlogJsonLdRoute
  '/superadmin/ga-debug': typeof SuperadminGaDebugRoute
  '/superadmin/ga-validate': typeof SuperadminGaValidateRoute
  '/blog': typeof BlogIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/beta-guide': typeof BetaGuideRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/find-booking': typeof FindBookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/use-cases': typeof UseCasesRoute
  '/what-is-mimmobook': typeof WhatIsMimmobookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/e2e/email-preview': typeof E2eEmailPreviewRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/retention': typeof LegalRetentionRoute
  '/legal/subprocessors': typeof LegalSubprocessorsRoute
  '/my-booking/$token': typeof MyBookingTokenRoute
  '/offer/$token': typeof OfferTokenRoute
  '/superadmin/blog-json-ld': typeof SuperadminBlogJsonLdRoute
  '/superadmin/ga-debug': typeof SuperadminGaDebugRoute
  '/superadmin/ga-validate': typeof SuperadminGaValidateRoute
  '/blog/': typeof BlogIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/beta-guide'
    | '/dashboard'
    | '/features'
    | '/find-booking'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/support'
    | '/use-cases'
    | '/what-is-mimmobook'
    | '/blog/$slug'
    | '/book/$slug'
    | '/e2e/email-preview'
    | '/legal/dpa'
    | '/legal/retention'
    | '/legal/subprocessors'
    | '/my-booking/$token'
    | '/offer/$token'
    | '/superadmin/blog-json-ld'
    | '/superadmin/ga-debug'
    | '/superadmin/ga-validate'
    | '/blog/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/beta-guide'
    | '/dashboard'
    | '/features'
    | '/find-booking'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/support'
    | '/use-cases'
    | '/what-is-mimmobook'
    | '/blog/$slug'
    | '/book/$slug'
    | '/e2e/email-preview'
    | '/legal/dpa'
    | '/legal/retention'
    | '/legal/subprocessors'
    | '/my-booking/$token'
    | '/offer/$token'
    | '/superadmin/blog-json-ld'
    | '/superadmin/ga-debug'
    | '/superadmin/ga-validate'
    | '/blog'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/beta-guide'
    | '/dashboard'
    | '/features'
    | '/find-booking'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/support'
    | '/use-cases'
    | '/what-is-mimmobook'
    | '/blog/$slug'
    | '/book/$slug'
    | '/e2e/email-preview'
    | '/legal/dpa'
    | '/legal/retention'
    | '/legal/subprocessors'
    | '/my-booking/$token'
    | '/offer/$token'
    | '/superadmin/blog-json-ld'
    | '/superadmin/ga-debug'
    | '/superadmin/ga-validate'
    | '/blog/'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  BetaGuideRoute: typeof BetaGuideRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  FindBookingRoute: typeof FindBookingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  UseCasesRoute: typeof UseCasesRoute
  WhatIsMimmobookRoute: typeof WhatIsMimmobookRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BookSlugRoute: typeof BookSlugRoute
  E2eEmailPreviewRoute: typeof E2eEmailPreviewRoute
  LegalDpaRoute: typeof LegalDpaRoute
  LegalRetentionRoute: typeof LegalRetentionRoute
  LegalSubprocessorsRoute: typeof LegalSubprocessorsRoute
  MyBookingTokenRoute: typeof MyBookingTokenRoute
  OfferTokenRoute: typeof OfferTokenRoute
  SuperadminBlogJsonLdRoute: typeof SuperadminBlogJsonLdRoute
  SuperadminGaDebugRoute: typeof SuperadminGaDebugRoute
  SuperadminGaValidateRoute: typeof SuperadminGaValidateRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta-guide': {
      id: '/beta-guide'
      path: '/beta-guide'
      fullPath: '/beta-guide'
      preLoaderRoute: typeof BetaGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-booking': {
      id: '/find-booking'
      path: '/find-booking'
      fullPath: '/find-booking'
      preLoaderRoute: typeof FindBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-mimmobook': {
      id: '/what-is-mimmobook'
      path: '/what-is-mimmobook'
      fullPath: '/what-is-mimmobook'
      preLoaderRoute: typeof WhatIsMimmobookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/email-preview': {
      id: '/e2e/email-preview'
      path: '/e2e/email-preview'
      fullPath: '/e2e/email-preview'
      preLoaderRoute: typeof E2eEmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/legal/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/retention': {
      id: '/legal/retention'
      path: '/legal/retention'
      fullPath: '/legal/retention'
      preLoaderRoute: typeof LegalRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/subprocessors': {
      id: '/legal/subprocessors'
      path: '/legal/subprocessors'
      fullPath: '/legal/subprocessors'
      preLoaderRoute: typeof LegalSubprocessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-booking/$token': {
      id: '/my-booking/$token'
      path: '/my-booking/$token'
      fullPath: '/my-booking/$token'
      preLoaderRoute: typeof MyBookingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$token': {
      id: '/offer/$token'
      path: '/offer/$token'
      fullPath: '/offer/$token'
      preLoaderRoute: typeof OfferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/blog-json-ld': {
      id: '/superadmin/blog-json-ld'
      path: '/superadmin/blog-json-ld'
      fullPath: '/superadmin/blog-json-ld'
      preLoaderRoute: typeof SuperadminBlogJsonLdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/ga-debug': {
      id: '/superadmin/ga-debug'
      path: '/superadmin/ga-debug'
      fullPath: '/superadmin/ga-debug'
      preLoaderRoute: typeof SuperadminGaDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/ga-validate': {
      id: '/superadmin/ga-validate'
      path: '/superadmin/ga-validate'
      fullPath: '/superadmin/ga-validate'
      preLoaderRoute: typeof SuperadminGaValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  BetaGuideRoute: BetaGuideRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  FindBookingRoute: FindBookingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  UseCasesRoute: UseCasesRoute,
  WhatIsMimmobookRoute: WhatIsMimmobookRoute,
  BlogSlugRoute: BlogSlugRoute,
  BookSlugRoute: BookSlugRoute,
  E2eEmailPreviewRoute: E2eEmailPreviewRoute,
  LegalDpaRoute: LegalDpaRoute,
  LegalRetentionRoute: LegalRetentionRoute,
  LegalSubprocessorsRoute: LegalSubprocessorsRoute,
  MyBookingTokenRoute: MyBookingTokenRoute,
  OfferTokenRoute: OfferTokenRoute,
  SuperadminBlogJsonLdRoute: SuperadminBlogJsonLdRoute,
  SuperadminGaDebugRoute: SuperadminGaDebugRoute,
  SuperadminGaValidateRoute: SuperadminGaValidateRoute,
  BlogIndexRoute: BlogIndexRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
